# Generated by Django 3.2.8 on 2021-11-01 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_menu', models.CharField(max_length=65, verbose_name='parent menu')),
                ('name', models.CharField(max_length=65, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('price', models.FloatField(verbose_name='price')),
                ('cover', models.FileField(upload_to='products', verbose_name='cover')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='discount')),
                ('in_stock', models.BooleanField(default=True, verbose_name='in stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='edited at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.categorymodel', verbose_name='category')),
                ('color', models.ManyToManyField(related_name='products', to='product.ColorModel', verbose_name='color')),
                ('size', models.ManyToManyField(related_name='products', to='product.SizeModel', verbose_name='size')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='products', verbose_name='images')),
                ('description', models.TextField(verbose_name='description')),
                ('features', models.TextField(verbose_name='features')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.productmodel', verbose_name='title')),
            ],
            options={
                'verbose_name': 'product detail',
                'verbose_name_plural': 'product details',
            },
        ),
    ]
