# Generated by Django 3.2.8 on 2021-11-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productdetailmodel',
            name='features',
            field=models.TextField(blank=True, null=True, verbose_name='features'),
        ),
    ]
