# Generated by Django 3.2.8 on 2021-11-01 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211102_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productdetailmodel',
            name='features',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='features',
            field=models.TextField(blank=True, null=True, verbose_name='features'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.ManyToManyField(related_name='product', to='product.ColorModel', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(related_name='product', to='product.SizeModel', verbose_name='size'),
        ),
    ]
