# Generated by Django 3.2.8 on 2021-11-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popcategorymodel',
            options={'verbose_name': 'popular', 'verbose_name_plural': 'populars'},
        ),
    ]
