# Generated by Django 3.2.8 on 2022-10-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_popcategorymodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopCategoryModel',
            new_name='PopularModel',
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='banner'),
        ),
    ]
